### Generate BASIC PRG - Hello World Loop (JSON-RPC MCP)
POST http://localhost:8080/
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "tools/call",
  "params": {
    "name": "ultimate_generate_basic_prg",
    "arguments": {
      "basicSource": "10 PRINT \"HELLO WORLD\"\n20 GOTO 10"
    }
  }
}

###
### Generate BASIC PRG - Simple Print
POST http://localhost:8080/
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/call",
  "params": {
    "name": "ultimate_generate_basic_prg",
    "arguments": {
      "basicSource": "10 PRINT \"HI THERE\""
    }
  }
}

###
### Generate BASIC PRG - Variables and Math
POST http://localhost:8080/
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "tools/call",
  "params": {
    "name": "ultimate_generate_basic_prg",
    "arguments": {
      "basicSource": "10 X = 5\n20 Y = 10\n30 Z = X + Y\n40 PRINT Z"
    }
  }
}

###
### Generate BASIC PRG - Input and Loop
POST http://localhost:8080/
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "ultimate_generate_basic_prg",
    "arguments": {
      "basicSource": "10 INPUT \"ENTER NAME: \"; N$\n20 PRINT \"HELLO \" N$\n30 GOTO 10"
    }
  }
}

###
### Generate BASIC PRG - Invalid Syntax (Error Example)
POST http://localhost:8080/
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 5,
  "method": "tools/call",
  "params": {
    "name": "ultimate_generate_basic_prg",
    "arguments": {
      "basicSource": "10 PRINT\nGOTO"
    }
  }
}

###
### Run generated PRG:
### 1) Copy "prgDataBase64" from result.content[0].text JSON
### 2) Use it with ultimate_run_prg_binary (see TEST_GENERATE_BASIC_PRG.http)
